openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /api/auth/signup:
    post:
      tags:
        - auth
      summary: Auth Signup
      description: Permite crear una cuenta con los campos para nombre de usuario, correo electrónico y contraseña. El nombre y el correo electrónico deben ser únicos en la plataforma, mientras que la contraseña debe seguir unos lineamientos mínimos de seguridad. Adicionalmente, la clave debe ser solicitada dos veces para que el usuario confirme que la ingresa de forma correcta.
      operationId: auth_signup_api_auth_signup_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /api/auth/login:
    get:
      tags:
        - auth
      summary: Auth Login
      description: Permite recuperar el token de autorización para consumir los recursos del API suministrando el nombre de usuario y la contraseña de una cuenta previamente registrada.
      operationId: auth_login_api_auth_login_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /api/tasks:
    get:
      tags:
        - tasks
      summary: Read Tasks
      description: Permite recuperar todas las tareas de edición de un usuario autorizado en la aplicación.
      operationId: read_tasks_api_tasks_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
    post:
      tags:
        - tasks
      summary: Crear Tasks
      description: Permite crear una nueva tarea de edición de video. El usuario requiere autorización.
      operationId: crear_tasks_api_tasks_post
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_crear_tasks_api_tasks_post'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/tasks/{id_task}:
    get:
      tags:
        - tasks
      summary: Read Task By Id
      description: Permite recuperar la información de una tarea en la aplicación. El usuario requiere autorización.
      operationId: read_task_by_id_api_tasks__id_task__get
      parameters:
        - name: id_task
          in: path
          required: true
          schema:
            type: string
            title: Id Task
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    delete:
      tags:
        - tasks
      summary: Delete Task By Id
      description: Permite eliminar una tarea en la aplicación. El usuario requiere autorización.
      operationId: delete_task_by_id_api_tasks__id_task__delete
      parameters:
        - name: id_task
          in: path
          required: true
          schema:
            type: string
            title: Id Task
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/tasks/to-processed/{id_task}:
    put:
      tags:
        - tasks
      summary: Update Task To Processed
      description: Permite recuperar la información de una tarea en la aplicación. El usuario requiere autorización.
      operationId: update_task_to_processed_api_tasks_to_processed__id_task__put
      parameters:
        - name: id_task
          in: path
          required: true
          schema:
            type: string
            title: Id Task
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    Body_crear_tasks_api_tasks_post:
      type: object
      properties:
        file:
          type: string
          format: binary
          title: File
      required:
        - file
      title: Body_crear_tasks_api_tasks_post
    HTTPValidationError:
      type: object
      properties:
        detail:
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
      title: HTTPValidationError
    ValidationError:
      type: object
      properties:
        loc:
          type: array
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          type: string
        type:
          type: string
      required:
        - loc
        - msg
        - type
      title: ValidationError
